services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zeppelin
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./logs:/app/logs
    working_dir: /app/src
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/src
    command: supervisord -c /etc/supervisord.conf

  db:
    image: postgres:15
    container_name: db_zeppelin
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: redis_zeppelin
    ports:
      - "6379:6379"
    restart: always

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flower_zeppelin
    command: celery --broker=redis://redis:6379/0 -A zeppelin flower --port=5555
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    working_dir: /app/src
    depends_on:
      - redis
      - app
    env_file:
      - .env

volumes:
  postgres_data:
