services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zeppelin
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./logs:/app/logs
    working_dir: /app/src
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/src
    command: supervisord -c /etc/supervisord.conf

  db:
    image: postgres:15
    container_name: zeppelin-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env

  
  
volumes:
  postgres_data:  
